### PR TITLE
Versions.props cleanup

### PR DESCRIPTION
**Pull request by jcagme**
Remove `RestoreSources` from Versions.props in order to complete [step 2](https://github.com/dotnet/arcade/blob/master/Documentation/RestoreSourcesUpdateStatus.md#part-2)

### CODE REVIEW

**Comment by jcagme** [comment]
FYI @tmat

**Comment by jcagme** [comment]
Also need help getting this merged.

**Comment by tmat** [comment]
The PR is failing. I think that might be because Arcade wasn't updated: https://github.com/dotnet/symreader-portable/pull/219

You might need to update nuget.config in the Arcade update PR.

**Comment by jcagme** [comment]
@tmat PR now works after updating the dependencies to latest, could you please merge this one and close #219?

**Pull request merged**
